name: golangci-lint
on:
  pull_request:
    branches: [ '**' ]
env:
  GOPRIVATE: github.com/DIMO-Network
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  golangci:
    runs-on: self-hosted

    name: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golangci-lint
        run: make tools-golangci-lint

      - name: Run golangci-lint
        run: make lint
